// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzPF5tP-t_DeaYyp4jB4YYEekkqAy5Lg',
    appId: '1:1005603986477:web:c0f4399fff7ea4e0bcaca4',
    messagingSenderId: '1005603986477',
    projectId: 'login-firebase-1-ae0ea',
    authDomain: 'login-firebase-1-ae0ea.firebaseapp.com',
    storageBucket: 'login-firebase-1-ae0ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlg2GkH-ybqcAB6-gvxtkmzYMehsbexqY',
    appId: '1:1005603986477:android:9ae607f8307598e9bcaca4',
    messagingSenderId: '1005603986477',
    projectId: 'login-firebase-1-ae0ea',
    storageBucket: 'login-firebase-1-ae0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgoJzcrab2iZru-jfSAOU6OY5gsuDSkc',
    appId: '1:1005603986477:ios:4cee437b1f0224c2bcaca4',
    messagingSenderId: '1005603986477',
    projectId: 'login-firebase-1-ae0ea',
    storageBucket: 'login-firebase-1-ae0ea.appspot.com',
    iosClientId: '1005603986477-7ho7q3v77c6j307ob84ck3olken25d23.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgoJzcrab2iZru-jfSAOU6OY5gsuDSkc',
    appId: '1:1005603986477:ios:1bffdf67f8552adfbcaca4',
    messagingSenderId: '1005603986477',
    projectId: 'login-firebase-1-ae0ea',
    storageBucket: 'login-firebase-1-ae0ea.appspot.com',
    iosClientId: '1005603986477-kdb4paj2na2rtobnkgohapalv8q1m153.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginWithFirebase.RunnerTests',
  );
}
